export const GET_RESOURCE_DATA_BEGIN = 'GET_RESOURCE_DATA_BEGIN';
export const GET_RESOURCE_DATA_SUCCESS = 'GET_RESOURCE_DATA_SUCCESS';
export const GET_RESOURCE_DATA_ERROR = 'GET_RESOURCE_DATA_ERROR';

export const GET_PARTNER_DATA_BEGIN = 'GET_PARTNER_DATA_BEGIN';
export const GET_PARTNER_DATA_SUCCESS = 'GET_PARTNER_DATA_SUCCESS';
export const GET_PARTNER_DATA_ERROR = 'GET_PARTNER_DATA_ERROR';
export const CREATE_PARTNER_BEGIN = 'CREATE_PARTNER_BEGIN';
export const CREATE_PARTNER_SUCCESS = 'CREATE_PARTNER_SUCCESS';
export const CREATE_PARTNER_ERROR = 'CREATE_PARTNER_ERROR';

export const CREATE_INNOVATION_BEGIN = 'CREATE_INNOVATION_BEGIN';
export const CREATE_INNOVATION_SUCCESS = 'CREATE_INNOVATION_SUCCESS';
export const CREATE_INNOVATION_ERROR = 'CREATE_INNOVATION_ERROR';
export const GET_INNOVATION_DATA_BEGIN = 'GET_INNOVATION_DATA_BEGIN';
export const GET_INNOVATION_DATA_SUCCESS = 'GET_INNOVATION_DATA_SUCCESS';
export const GET_INNOVATION_DATA_ERROR = 'GET_INNOVATION_DATA_ERROR';
export const GET_INNOVATIONS_LIST_BEGIN = 'GET_INNOVATIONS_LIST_BEGIN';
export const GET_INNOVATIONS_LIST_SUCCESS = 'GET_INNOVATIONS_LIST_SUCCESS';
export const GET_INNOVATIONS_LIST_ERROR = 'GET_INNOVATIONS_LIST_ERROR';
export const EDIT_INNOVATION_BEGIN = 'UPDATE_INNOVATION_BEGIN';
export const EDIT_INNOVATION_SUCCESS = 'UPDATE_INNOVATION_SUCCESS';
export const EDIT_INNOVATION_ERROR = 'UPDATE_INNOVATION_ERROR';
export const EDIT_INNOVATION_KEYDATES_BEGIN = 'UPDATE_INNOVATION_KEYDATES_BEGIN';
export const EDIT_INNOVATION_KEYDATES_SUCCESS = 'UPDATE_INNOVATION_KEYDATES_SUCCESS';
export const EDIT_INNOVATION_KEYDATES_ERROR = 'UPDATE_INNOVATION_KEYDATES_ERROR';
export const DELETE_INNOVATION_BEGIN = 'DELETE_INNOVATION_BEGIN';
export const DELETE_INNOVATION_SUCCESS = 'DELETE_INNOVATION_SUCCESS';
export const DELETE_INNOVATION_ERROR = 'DELETE_INNOVATION_ERROR';

export const CREATE_CONCEPT_BEGIN = 'CREATE_CONCEPT_BEGIN';
export const CREATE_CONCEPT_SUCCESS = 'CREATE_CONCEPT_SUCCESS';
export const CREATE_CONCEPT_ERROR = 'CREATE_CONCEPT_ERROR';
export const GET_CONCEPT_BEGIN = 'GET_CONCEPT_BEGIN';
export const GET_CONCEPT_SUCCESS = 'GET_CONCEPT_SUCCESS';
export const GET_CONCEPT_ERROR = 'GET_CONCEPT_ERROR';
export const GET_CONCEPTS_BEGIN = 'GET_CONCEPTS_BEGIN';
export const GET_CONCEPTS_SUCCESS = 'GET_CONCEPTS_SUCCESS';
export const GET_CONCEPTS_ERROR = 'GET_CONCEPTS_ERROR';

export const CHECK_BREAKPOINT = 'CHECK_BREAKPOINT';

export const EDIT_CONCEPT_BEGIN = 'UPDATE_CONCEPT_BEGIN';
export const EDIT_CONCEPT_SUCCESS = 'UPDATE_CONCEPT_SUCCESS';
export const EDIT_CONCEPT_ERROR = 'UPDATE_CONCEPT_ERROR';
export const DELETE_CONCEPT_BEGIN = 'DELETE_CONCEPT_BEGIN';
export const DELETE_CONCEPT_SUCCESS = 'DELETE_CONCEPT_SUCCESS';
export const DELETE_CONCEPT_ERROR = 'DELETE_CONCEPT_ERROR';

export const REQUEST_ALL_USERS_BEGIN = 'REQUEST_ALL_USERS_BEGIN';
export const REQUEST_ALL_USERS_SUCCESS = 'REQUEST_ALL_USERS_SUCCESS';
export const REQUEST_ALL_USERS_ERROR = 'REQUEST_ALL_USERS_ERROR';
export const REQUEST_INNOVATION_USERS_BEGIN = 'REQUEST_INNOVATION_USERS_BEGIN';
export const REQUEST_INNOVATION_USERS_SUCCESS = 'REQUEST_INNOVATION_USERS_SUCCESS';
export const REQUEST_INNOVATION_USERS_ERROR = 'REQUEST_INNOVATION_USERS_ERROR';
export const INVITE_INNOVATION_USERS_BEGIN = 'INVITE_INNOVATION_USERS_BEGIN';
export const INVITE_INNOVATION_USERS_SUCCESS = 'INVITE_INNOVATION_USERS_SUCCESS';
export const INVITE_INNOVATION_USERS_ERROR = 'INVITE_INNOVATION_USERS_ERROR';

export const AUTH_FROM_JWT_BEGIN = 'AUTH_FROM_JWT_BEGIN';
export const AUTH_FROM_JWT_SUCCESS = 'AUTH_FROM_JWT_SUCCESS';
export const AUTH_FROM_JWT_ERROR = 'AUTH_FROM_JWT_ERROR';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
