export const GET_PORTFOLIO_BEGIN = 'GET_PORTFOLIO_BEGIN';
export const GET_PORTFOLIO_SUCCESS = 'GET_PORTFOLIO_SUCCESS';
export const GET_PORTFOLIO_ERROR = 'GET_PORTFOLIO_ERROR';

export const GET_CONCEPTS_BEGIN = 'GET_CONCEPTS_BEGIN';
export const GET_CONCEPTS_SUCCESS = 'GET_CONCEPTS_SUCCESS';
export const GET_CONCEPTS_ERROR = 'GET_CONCEPTS_ERROR';
